alproton/maplibre-native

include/mbgl/util/platform.hpp
platform/android/MapLibreAndroid/src/cpp/geojson/feature.cpp
platform/android/MapLibreAndroid/src/cpp/geojson/geometry_collection.cpp
platform/android/MapLibreAndroid/src/cpp/map_renderer.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/src/thread.cpp
platform/darwin/src/nsthread.mm
platform/default/src/mbgl/util/thread.cpp
platform/qt/src/mbgl/thread.cpp
platform/windows/include/thread.h
platform/windows/src/thread.cpp

In CPU bound situations, Android apps with many active threads can become unresponsive (hitching). Within MapLibre the render thread is the thread where hitches are noticeable. This PR sets a high priority for the render thread to reduce hitches when the app is CPU limited.

Increase thread priority for the rendering thread

---

platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationAnimatorCustomPuck.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationComponent.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/Utils.java

Add error checking related to puck rendering errors.
If the location fed to MapLibre is wrong (contains NaN), an error is logged and the location is ignored.
If a NaN is detect downstream an fatal exception is thrown

Add location NaN error checking

---

include/mbgl/map/map.hpp
include/mbgl/map/map_lod_shift.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapLibreMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/glfw/glfw_view.cpp
src/mbgl/map/map.cpp
src/mbgl/map/map_impl.hpp
src/mbgl/renderer/tile_parameters.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/update_parameters.hpp

Allow finer control of LOD shift by passing an array of shifts at different zoom levels instead of a global shift
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/7)

Multi stops lod shift

---

include/mbgl/route/route.hpp
src/mbgl/route/route.cpp
src/mbgl/route/route_segment.cpp

Issues:
The infamous gradient bug were due to following situations:
1) some of the points in the route  segments did not lie on the route or even close to the entire route. I loop through each route segment point to store its normalized distance within route. Since this point was not found close to the entire route, all of the route point intervals  were searched and the "distance so far" variable went full to the full distance of the route and incorrectly calculated that the point's distance is 1. This caused problems when calculating the gradient.
2) last attempt did resolve for overlapping route segments but there was a missing = when checking if the routes intersected.
Fixing these two helped resolve the bug that was captured via snapshot capturing system implemented last release.

fixes for the gradient bug

---

platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/glfw/glfw_view.cpp
platform/glfw/glfw_view.hpp
src/mbgl/route/route_manager.cpp

Issue: to easily parse the stats, the stats string is pressed into one line with no next lines or tabs. This is done so that integration team can easily read the string from logs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/14)

added support for oneline stats

---

include/mbgl/gfx/renderer_backend.hpp

Order of destruction was wrong. Custom objects must be destroyed after the gl context because they call `glDeleteTexture`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/23)

Fix shutdown crash

---

platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/camera/CameraPosition.kt
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/geometry/LatLng.kt
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/Transform.java

Make sure we don't keep calling `onCameraMove` repeatedly even when the camera isn't moving by adding an epsilon when checking for Camera changes and also consider the fact that `CameraPosition.Builder` can build a camera with partially set parameters
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/21)

Fix repeating onCameraMove

---

platform/glfw/glfw_view.hpp
src/mbgl/route/route.cpp

This PR adds the following:
* Normalize the incoming vector when converting cartesian coordinate to latlon.
* minor refactoring for glfw scrubbing captured nav stops replays
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/25)

fixes for slerp

---

platform/glfw/glfw_view.cpp

This PR fixes the compilation error in rivmain due to a missed commit prior.
Adds support for scrubbing forward and backward of nav stops data captured in a routes snapshot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/27)

Missed commit to rivmain

---

platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationAnimatorCustomPuck.java

Check the style is loaded `style.isFullyLoaded()` is `true` before rendering the puck. This avoids a rare crash similar to #3348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/30)

Fix a crash related to rendering the puck before the style is loaded

---

include/mbgl/route/route.hpp
include/mbgl/route/route_manager.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/android/MapLibreAndroidTestApp/src/main/java/org/maplibre/android/testapp/activity/routes/RouteActivity.kt
platform/android/MapLibreAndroidTestApp/src/main/java/org/maplibre/android/testapp/activity/routes/RouteUtils.kt
platform/android/MapLibreAndroidTestApp/src/main/res/layout/activity_routes.xml
platform/glfw/glfw_backend.hpp
platform/glfw/glfw_gl_backend.cpp
platform/glfw/glfw_gl_backend.hpp
platform/glfw/glfw_view.cpp
platform/glfw/glfw_view.hpp
src/mbgl/route/route.cpp
src/mbgl/route/route_manager.cpp

This PR has the following supports:
1. Fix for the purple route segment, kotlin sends us RGB but our jni color converter expects ARGB. Fix is to set alpha to 1.
2. Added support for puck rendering in GLFW and android
3. Currently the vanishing route ID was in MapView.java, it is now pushed into RouteManager for better maintainance
4. Removed the expensive formatting string stream used to format logs.
5. Added metrics to measure vanishing route for long distances
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/35)

Miscellaneous work on route rendering

---

include/mbgl/route/route_segment.hpp
src/mbgl/route/route.cpp
src/mbgl/route/route_segment.cpp

Problem:
Report was made that sometimes the route segments do not closely match the traffic data in google maps.
Solution:
We need the normalized position of lat lons of route segments for gradient colors. These normalized positions were calculate in lat lon space and may not spatially accurate based on distances. This is now following the fine precision that vanishing route uses for better approximation of normalization of the lat lons along the route.
NB:
In this PR, if any route segment position has nan values , the entire route segment is rejected. The app code is sending only 2 points and we need a minimum of 2 points for a route segment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

support for fine precision route segments

---

include/mbgl/renderer/renderer.hpp
include/mbgl/renderer/tile_cache_settings.hpp
platform/android/MapLibreAndroid/src/cpp/android_renderer_frontend.cpp
platform/android/MapLibreAndroid/src/cpp/android_renderer_frontend.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/SymbolLocationLayerRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapLibreMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/TileCacheSettings.java
src/mbgl/map/map_impl.cpp
src/mbgl/renderer/layers/render_background_layer.cpp
src/mbgl/renderer/layers/render_background_layer.hpp
src/mbgl/renderer/layers/render_fill_layer.hpp
src/mbgl/renderer/render_layer.hpp
src/mbgl/renderer/render_orchestrator.cpp
src/mbgl/renderer/render_orchestrator.hpp
src/mbgl/renderer/render_source.hpp
src/mbgl/renderer/renderer.cpp
src/mbgl/renderer/sources/render_tile_source.hpp
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp
src/mbgl/renderer/update_parameters.hpp
src/mbgl/tile/tile_cache.cpp
src/mbgl/tile/tile_cache.hpp

When a tile is missing (being downloaded) the background color defined in the style is used. This PR adds the possibility to define another background color set using the API `setBackgroundClearColor`. When the tile is available the style background color is used otherwise the color set with `setBackgroundClearColor` is used for missing tiles
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/39)

Add background color for missing tiles

---

include/mbgl/renderer/tile_cache_settings.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/TileCacheSettings.java
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/tile/tile_cache.cpp
src/mbgl/tile/tile_cache.hpp

Option to reduce tile cache memory usage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/44)

Add an option to un-cache old tiles to reduce memory usage

---

src/mbgl/tile/tile_cache.cpp

There was a minor performance bug in https://github.com/alproton/maplibre-native/pull/44 causing `releaseOldTiles` to never early out and compute `oldestTile` timestamp every frame.
This change ensures `oldestTile` is initialized before computing the oldest tile timestamp.
After this change when `cachedTileMaxAge` is to set to a value, e.g. 1 minute, `releaseOldTiles` will execute its code every minute on average
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/45)

Early out from releaseOldTiles

---

src/mbgl/renderer/tile_parameters.hpp
src/mbgl/tile/tile_cache.cpp
src/mbgl/tile/tile_cache.hpp

This avoids a dangling pointer
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/53)

Fix tile cache dangling reference

---

include/mbgl/gfx/polyline_generator.hpp
include/mbgl/route/route.hpp
include/mbgl/shaders/gl/drawable_line_gradient.hpp
platform/glfw/glfw_backend.hpp
platform/glfw/glfw_gl_backend.cpp
platform/glfw/glfw_view.cpp
platform/glfw/glfw_view.hpp
src/mbgl/gfx/polyline_generator.cpp
src/mbgl/gl/custom_puck.cpp
src/mbgl/layout/pattern_layout.hpp
src/mbgl/programs/attributes.hpp
src/mbgl/programs/line_program.cpp
src/mbgl/programs/line_program.hpp
src/mbgl/renderer/bucket.hpp
src/mbgl/renderer/buckets/line_bucket.cpp
src/mbgl/renderer/buckets/line_bucket.hpp
src/mbgl/renderer/layers/render_line_layer.cpp
src/mbgl/route/route.cpp
src/mbgl/route/route_manager.cpp
src/mbgl/shaders/gl/shader_info.cpp

This PR adds:
* support for web mercator projection test case in glfwview
* removal of all of the code changes made to support high precision line so far vertex attribute as it was identified that it did little to improve the vanishing gap issue and instead caused problems for traffic visualization

Sid revert highp linesofar

---

src/mbgl/gfx/custom_puck.cpp

Puck looping animations are working fine but for animations that run once the epoch time of the animation needs to be set.
This PR adds a small change to initialize the the epoch time when a puck state is set

Fix non-looping puck animations

---

platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/IndicatorLocationLayerRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationComponent.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationLayerController.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationLayerRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/SymbolLocationLayerRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java

This is a performance optimization. When the custom puck is used there's no need to run geojson refreshes for the location component since geojson is not really used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/61)

Disable Location geojson refreshes when custom puck is used

---

include/mbgl/route/route.hpp
include/mbgl/route/route_manager.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMap.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/android/MapLibreAndroidTestApp/src/main/java/org/maplibre/android/testapp/activity/routes/RouteUtils.kt
platform/glfw/tests/route_add_traffic_test.cpp
platform/glfw/tests/route_pick_test.cpp
platform/glfw/tests/route_traffic_priority_test.cpp
src/mbgl/route/route.cpp
src/mbgl/route/route_manager.cpp

Nav side uses fractional indices for traffic segments that is sent directly from google auto SDK which is a polyline index and local fractional value within that polyline index. Before that nav was unnecessarily calculating points on the route that represented a traffic segment. This was done prior to create polylines for traffic segments which is not how we render traffic in MLN for routes.
MLN route API supported both. We have code in Nav that now passes efficiently directly from auto sdk. There is no reason keep around unused and un-needed code.
[Passed all graphics tests]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alproton/maplibre-native/62)

removed unused method of traffic segments rendering

---

include/mbgl/gfx/custom_puck.hpp
include/mbgl/util/thread.hpp
platform/android/MapLibreAndroid/src/cpp/map_renderer.cpp
platform/android/MapLibreAndroid/src/cpp/map_renderer.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/location/LocationCameraController.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapLibreMapOptions.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/renderer/MapRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/renderer/surfaceview/SurfaceViewMapRenderer.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/renderer/textureview/TextureViewMapRenderer.java
platform/android/MapLibreAndroid/src/opengl/java/org/maplibre/android/maps/renderer/MapRendererFactory.java
platform/android/MapLibreAndroid/src/opengl/java/org/maplibre/android/maps/renderer/surfaceview/GLSurfaceViewMapRenderer.java
platform/android/MapLibreAndroid/src/vulkan/java/org/maplibre/android/maps/renderer/MapRendererFactory.java
platform/android/MapLibreAndroid/src/vulkan/java/org/maplibre/android/maps/renderer/surfaceview/VulkanSurfaceViewMapRenderer.java
platform/android/src/thread.cpp
platform/default/src/mbgl/util/thread.cpp
platform/windows/src/thread.cpp
src/mbgl/gfx/custom_puck.cpp
src/mbgl/util/thread.cpp

for debugging and profiling purpose, we add a flag to override the default thread priority behavior by either forcing all thread to run with high or low priority. The override can be optionally passed to MapLibre using the code:
```
MapLibreMapOptions.createFromAttributes(context).apply {
threadPriorityOverride(MapLibreMapOptions.ThreadPriorityOverride.FORCE_LOW)
}
```

Add thread priority override

---

platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/MapView.java

There's nothing that guarantees the rendering of the next frame when the custom puck is used unlike geojson. This is  minor change that ensures correctness

Make sure we always render the next frame after puck updates

---

include/mbgl/renderer/tile_cache_settings.hpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.cpp
platform/android/MapLibreAndroid/src/cpp/native_map_view.hpp
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/NativeMapView.java
platform/android/MapLibreAndroid/src/main/java/org/maplibre/android/maps/TileCacheSettings.java
src/mbgl/renderer/tile_pyramid.cpp
src/mbgl/renderer/tile_pyramid.hpp

Render tiles (already have GPU resources and are renderable) are reused when the camera is not moving without making a cache request for these tiles. Short lived tiles (have a short http max age and http etag often expire) needs to be re downloaded.
A good example of short lived tiles are real time traffic data stored as a tile source.
Adding expiration logic to the render tiles is not straightforward. However a straightforward approach is to simply clear render tiles if they are short lived at a constant interval if the camera isn't changing (the ideal tiles remain unchanged between frames).
This PR exposes the option `TileCacheSettings::renderTileMaxAge` to the client app to set a max age for rendering tiles.

Add an option to invalidate render tiles
